# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hO7yozNlpCV5Dhe0ab-5pTPPG_3h4IBc
"""

import numpy as np
import matplotlib.pyplot as plt
A, B, C, D = (-1.035, 3.863), (0, 0), (5, 0), (3.871, 6.401)


def line_gen(C1, C2):
    return ((C1[0], C2[0]), (C1[1], C2[1]))

l1 = line_gen(B, C)
l2 = line_gen(C, D)
l3 = line_gen(B, A)
l4 = line_gen(D, A)
l5 = line_gen(D, B)


def drawLine(line):
    plt.plot(line[0], line[1])
    
def drawVertix(coordinate, name):
    plt.plot(coordinate[0], coordinate[1], 'o')
    plt.text(coordinate[0] * (1 + 0.1), coordinate[1] * (1 - 0.1) , name)


# drawing Quadrilateral
drawLine(l1)
drawLine(l2)
drawLine(l3)
drawLine(l4)
drawLine(l5)

# plotting vertices
drawVertix(A, "A")
drawVertix(B, "B")
drawVertix(C, "C")
drawVertix(D, "D")


plt.xlabel('x - axis')
plt.ylabel('y - axis')
plt.title('Quadrilateral')
plt.grid()
plt.show()